config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from core.erp.views.calendario.views import page_not_found404

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.homepage.urls')),
    # path('login/', LoginFormView.as_view()),
    # path('login/', include('core.login.urls')),
    path('admin/', admin.site.urls),
    path('erp/', include('core.erp.urls')),
    # path('reports/', include('core.reports.urls')),
    path('user/', include('core.user.urls')),
]

handler404 = page_not_found404

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/erp/urls.py
from django.urls import path

from core.erp.views.dashboard.views import DashboardView

from core.erp.views.habitacion.habitacion.views import *
from core.erp.views.habitacion.piso.views import *
from core.erp.views.habitacion.servicio.views import *
from core.erp.views.habitacion.tipo.views import *

from core.erp.views.calendario.views import *
from core.erp.views.recepcion.views import *
from core.erp.views.pago.views import *

app_name = "erp"

urlpatterns = [
    # home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    # Calendario
    path('calendario/', CalendarioListView.as_view(), name='calendario'),
    ########################## HABITACION ##############################
    # habitacion
    path('habitacion/list/', HabitacionListView.as_view(), name='habitacion_list'),
    path('habitacion/add/', HabitacionCreateView.as_view(), name='habitacion_create'),
    path('habitacion/update/<int:pk>/', HabitacionUpdateView.as_view(), name='habitacion_update'),
    path('habitacion/delete/<int:pk>/', HabitacionDeleteView.as_view(), name='habitacion_delete'),
    # piso
    path('habitacion/piso/list/', PisoListView.as_view(), name='piso_list'),
    path('habitacion/piso/add/', PisoCreateView.as_view(), name='piso_create'),
    path('habitacion/piso/update/<int:pk>/', PisoUpdateView.as_view(), name='piso_update'),
    path('habitacion/piso/delete/<int:pk>/', PisoDeleteView.as_view(), name='piso_delete'),
    # servicio habitacion
    path('habitacion/servicio/list/', ServicioHabitacionListView.as_view(), name='servicio_habitacion_list'),
    path('habitacion/servicio/add/', ServicioHabitacionCreateView.as_view(), name='servicio_habitacion_create'),
    path('habitacion/servicio/update/<int:pk>/', ServicioHabitacionUpdateView.as_view(), name='servicio_habitacion_update'),
    path('habitacion/servicio/delete/<int:pk>/', ServicioHabitacionDeleteView.as_view(), name='servicio_habitacion_delete'),
    # tipo habitacion
    path('habitacion/tipo/list/', TipoHabitacionListView.as_view(), name='tipo_habitacion_list'),
    path('habitacion/tipo/add/', TipoHabitacionCreateView.as_view(), name='tipo_habitacion_create'),
    path('habitacion/tipo/update/<int:pk>/', TipoHabitacionUpdateView.as_view(), name='tipo_habitacion_update'),
    path('habitacion/tipo/delete/<int:pk>/', TipoHabitacionDeleteView.as_view(), name='tipo_habitacion_delete'),
    ########################## RESERVAS ##############################
    # reception
    path('recepcion/', RecepcionView.as_view(), name='recepcion'),
    path('check_out/', CheckOutView.as_view(), name='check_out'),
    path('check_in/', CheckInView.as_view(), name='check_in'),
    # path('check_out/pago/<int:pk>/', PagoReservaCreateView.as_view(), name='pago_reserva'),
    path('reserva/info/<int:pk>/', InfoReservaView.as_view(), name='info_reserva'),
    path('recepcion/list/', ReservaListView.as_view(), name='recepcion_list'),
    path('recepcion/add/<int:pk>/', ReservaCreateView.as_view(), name='recepcion_create'),
    path('recepcion/update/<int:pk>/', ReservaUpdateView.as_view(), name='recepcion_update'),
    path('recepcion/delete/<int:pk>/', ReservaDeleteView.as_view(), name='recepcion_delete'),

    ########################## PAGO RESERVA ##############################
    # pago reserva
    path('reserva/pago/list/', PagoReservaListView.as_view(), name='pago_reserva_list'),
    # path('guest/add/', GuestCreateView.as_view(), name='guest_create'),
    path('reserva/pago/update/<int:pk>/', PagoReservaUpdateView.as_view(), name='pago_reserva_update'),
    path('reserva/pago/delete/<int:pk>/', PagoReservaDeleteView.as_view(), name='pago_reserva_delete'),
]

core/user/urls.py
from django.urls import path

from core.user.views import *

app_name = 'user'

urlpatterns = [
    #user
    path('list/', UserListView.as_view(), name='user_list'),
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('change/password/', UserChangePasswordView.as_view(), name='user_change_password'),
    path('logout/', LogoutRedirectView.as_view(), name='logout'),
]

templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'vtc/header.html' %}
        <!-- Sidebar -->
        {% include 'vtc/sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header pb-0">
                <div class="container-fluid">
                    <div class="card">
                            <div class="col-sm-12">
                                <ol class="breadcrumb float-sm-left m-2">
                                    <li class="breadcrumb-item"><a href="{% url 'erp:dashboard' %}" class="text-secondary"><i class="fas fa-home"></i> Panel</a></li>
                                    <li class="breadcrumb-item"><a href="{{ list_url }}" class="text-secondary"><i class="{{ icon }}"></i> {{ entity }}</a></li>
                                </ol>
                            </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}

    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    </body>
{% endblock %}

templates/vtc/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'erp:dashboard' %}" class="nav-link">Home</a>
        </li>
        <li class="nav-item dropright">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"></i> Bienvenido {{ request.user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-header" style="font-size: 12px;">
                    Su último acceso fue {{ request.user.last_login }}
                </span>
                <div class="dropdown-divider"></div>
                <a href="{% url 'user:user_profile' %}" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                    <span class="float-right text-muted text-sm"></span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="{% url 'user:user_change_password' %}" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar password
                    <span class="float-right text-muted text-sm"></span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitira realizar diferentes actividades</p>
                </a>
            </div>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        {% if request.user.groups.all %}
        <li class="nav-item dropdown">
            <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
                class="nav-link  {% if request.user.groups.all.count > 1 %} dropdown-toggle{% endif %}">{{ request.session.group }}</a>
            {% if request.user.groups.all.count > 1 %}
            <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                style="left: 0px; right: inherit;">
                {% for g in request.user.groups.all %}
                {% if g.id != request.session.group.id %}
                <li><a href="{% url 'user:user_change_group' g.id %}" class="dropdown-item">{{ g.name }}</a>
                </li>
                {% endif %}
                {% endfor %}
            </ul>
            {% endif %}
        </li>
        {% endif %}

        <li class="nav-item">
            <a class="nav-link" href="{% url 'user:logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

templates/vtc/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="#" class="brand-link">
        <img src="{% static 'img/logo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
            style="opacity: .8">
        <span class="brand-text font-weight-light">Reserva Facil</span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ request.user.get_image }}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ request.user.get_full_name }}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Mantenimientos</li>
                <li class="nav-item">
                    <a href="{% url 'erp:calendario' %}" class="nav-link">
                        <i class="nav-icon fas fa-calendar-alt"></i>
                        <p>
                            Reserva
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-concierge-bell"></i>
                        <p>
                            Gestión
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview ml-4 pl-2">
                        <li class="nav-item">
                            <a href="{% url 'erp:recepcion' %}" class="nav-link">
                                <i class="nav-icon fas fa-door-open"></i>
                                <p>Recepción</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:recepcion_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-clipboard-list"></i>
                                <p>Listado</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:check_in' %}" class="nav-link">
                                <i class="nav-icon fas fa-sign-in-alt"></i>
                                <p>Entrada</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:check_out' %}" class="nav-link">
                                <i class="nav-icon fas fa-sign-out-alt"></i>
                                <p>Salida</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <!-- pagos -->
                <li class="nav-item">
                    <a href="{% url 'erp:pago_reserva_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-hand-holding-usd"></i>
                        <p>
                            Pagos
                        </p>
                    </a>
                </li>
                <!-- habitaciones -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-wrench"></i>
                        <p>
                            Mantenimiento
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview ml-4 pl-2">

                        <li class="nav-item">
                            <a href="{% url 'erp:habitacion_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-bed"></i>
                                <p>Habitaciones</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'erp:piso_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-hotel"></i>
                                <p>Pisos</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'erp:servicio_habitacion_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-thumbs-up"></i>
                                <p>Servicios</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'erp:tipo_habitacion_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-procedures"></i>
                                <p>Tipos</p>
                            </a>
                        </li>

                    </ul>
                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:dashboard' %}" class="nav-link">
                        <i class="nav-icon fas fa-chart-pie"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'user:user_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-user-friends"></i>
                        <p>
                            Usuarios
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>