config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from core.erp.views.calendario.views import page_not_found404

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.homepage.urls')),
    # path('login/', LoginFormView.as_view()),
    # path('login/', include('core.login.urls')),
    path('admin/', admin.site.urls),
    path('erp/', include('core.erp.urls')),
    # path('reports/', include('core.reports.urls')),
    path('user/', include('core.user.urls')),
]

handler404 = page_not_found404

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/homepage/urls.py
from django.urls import path
from core.homepage.views import *
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
# from django.conf.urls import url


urlpatterns = [
    # path('', index, name="index"),
    # path('register', register, name="register"),
    path('', inicio, name="inicio"),
    path('nosotros/', nosotros, name="nosotros"),
    path('login/', login, name="login"),
    path('register/', register, name="register"),
    path('modify/', modify, name="profileModify"),
    path('logout/', logout),
    path('reset/password_reset', PasswordResetView.as_view(template_name='departamento/registration/password_reset_forms.html', email_template_name="departamento/registration/password_reset_email.html"), name = 'password_reset'),
    path('reset/password_reset_done', PasswordResetDoneView.as_view(template_name='departamento/registration/password_reset_done.html'), name = 'password_reset_done'),
    # url(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name='departamento/registration/password_reset_confirms.html'), name = 'password_reset_confirm'),
    path('reset/done',PasswordResetCompleteView.as_view(template_name='departamento/registration/password_reset_complete.html') , name = 'password_reset_complete'),
    path('perfil_cliente/', ProfileView.as_view(), name='perfil_cliente')
]

core/homepage/models.py
import imp
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django import forms

User = get_user_model()

class Huesped(models.Model):
    tipo_documento_choices = {
    ('DNI', 'DNI'),
    ('pasaporte', 'Pasaporte'),
    ('carnet extranjeria', 'Carnet Extranjeria')
    }

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50, verbose_name='Nombre', blank=True, null=True)
    apellido = models.CharField(max_length=50, verbose_name='Apellido', blank=True, null=True)
    tipo_documento = models.CharField(max_length=25, choices=tipo_documento_choices, default="DNI", verbose_name="Tipo de Documento", blank=True, null=True)
    numero_documento = models.IntegerField(verbose_name="Numero de Documento", blank=True, null=True)
    email = models.EmailField(verbose_name='Email', blank=True, null=True)
    telefono = models.IntegerField(verbose_name="telefono", blank=True, null=True)
    
    def __str__(self):
        if self.nombre and self.apellido:
            return '%s %s' % (self.nombre, self.apellido)
        return self.user.username

    # def get_absolute_url(self):
    #     return reverse('perfil_cliente', args=[str(self.id)])

core/homepage/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from core.homepage.models import Huesped
from core.user.models import User


# Formulario de Login

class AFWithEmail(AuthenticationForm):
    # Ahora el campo username es de tipo email y cambiamos su texto
    username = forms.Field(label="Nombre usuario")

    class Meta:
        model = User
        fields = ["username", "password"]

# Formulario de Registro

class UCFWithEmail(UserCreationForm):
    # Establecemos que el campo username es tipo email y el nombre
    username = forms.Field(label="Nombre usuario")

    class Meta:
        model = User
        fields = ["username", "password1", "password2",
                  "first_name", "last_name", "email", "telefono"]

# Formulario de Modificación de Perfil

class profileModifyForm(forms.ModelForm):

    class Meta:
        model = Huesped
        fields = ["nombre","apellido","tipo_documento",
                "numero_documento", "email", "telefono"]
        
        widgets = {
            'nombre': forms.TextInput(attrs={'class' : 'form-control'}),
            'apellido': forms.TextInput(attrs={'class' : 'form-control'}),
            'tipo_documento': forms.TextInput(attrs={'class' : 'form-control'}),
            'numero_documento': forms.TextInput(attrs={'class' : 'form-control'}),
            'email': forms.TextInput(attrs={'class' : 'form-control'}),
            'telefono': forms.TextInput(attrs={'class' : 'form-control'}),

        }

    

core/homepage/views.py
from cProfile import Profile
from django.urls import reverse_lazy
from .forms import AFWithEmail, UCFWithEmail
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import login as do_login
from django.contrib.auth import logout as do_logout
from django.http import HttpResponse, response
from django.contrib import messages
from core.erp.models import Configuration, Habitacion,ImagenHabitacion,Reserva
from django.core.paginator import Paginator
from django.views.generic import UpdateView

import config.settings as setting

from .filters import *
from django.db.models import Q
from datetime import datetime
from .forms import profileModifyForm

from core.homepage.models import Huesped

# Vista principal y login.


def login(request):
  # Creamos el formulario de autenticación vacío
    form = AuthenticationForm()
    if request.method == "POST":
        # Añadimos los datos recibidos al formulario
        form = AuthenticationForm(data=request.POST)
        # Si el formulario es válido...
        if form.is_valid():
            # Recuperamos las credenciales validadas
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # Verificamos las credenciales del usuario
            user = authenticate(username=username, password=password)

            # Si existe el usuario
            if user is not None:
                # Hacemos el login manualmente
                do_login(request, user)
                # Y le redireccionamos a la portada
                for group in request.user.groups.all():
                    if  user.is_superuser or group.name == "Gestor":
                        return redirect('erp:dashboard')
                return redirect('inicio')
            else:
                messages.error(request, 'Usuario o contraseña incorrectos')

        else:
            messages.error(request, 'Los datos no son válidos')

    # Si llegamos al final renderizamos el formulario
    return render(request, 'departamento/login.html', {'form': form})

# Vista registro de usuarios.


def register(request):
    # Creamos el formulario de autenticación vacío
    form = UCFWithEmail()
    if request.method == "POST":
        # Añadimos los datos recibidos al formulario
        form = UCFWithEmail(data=request.POST)

        # Si el formulario es válido...
        if form.is_valid():


            # Creamos la nueva cuenta de usuario
            user = form.save()
            messages.success(
                request, f'Bienvenid@ {user.username}, ya eres parte de Reserva Fácil')

            # Si existe el usuario
            if user is not None:
                # Hacemos el login manualmente
                do_login(request, user)
                # Y le redireccionamos a la portada
                return redirect('inicio')
        else:
          messages.error(request, 'Usuario ya existente')

    # Si queremos borramos los campos de ayuda
    form.fields['username'].help_text = None
    form.fields['password1'].help_text = None
    form.fields['password2'].help_text = None

    # Si llegamos al final renderizamos el formulario
    return render(request, "departamento/registro.html", {'form': form})


#Cierre de sesión para los usuarios.


def logout(request):
    # Finalizamos la sesión
    do_logout(request)
    # Redireccionamos a la portada
    return redirect('/')


# class LogoutRedirectView(RedirectView):
#     pattern_name = 'inicio'

#     def dispatch(self, request, *args, **kwargs):
#         logout(self.request)
#         return super().dispatch(request, *args, **kwargs)


# Vista página de inicio.


def inicio(request):
    configuracion = Configuration.objects.last()
    filtro = FiltroHabitacion(request.GET,queryset=Habitacion.objects.filter(activo=True).order_by('numero_habitacion'))
    page = request.GET.get('page', 1)
    try:
        paginator = Paginator(filtro.qs, 6)
        qs = paginator.get_page(page) 
    except:
        raise response.Http404
    #Elementos Filtro Fecha
    reservas = Reserva.objects.filter(check_out__gte=datetime.now()).order_by('habitacion__numero_habitacion')
    checkin = request.GET.get('checkin')
    checkout = request.GET.get('checkout')
    if  valid_param(checkin):
        if valid_param(checkout):
            if(checkout >= checkin):
                reservas = reservas.filter(Q(check_in__lte=checkin) & Q(check_out__gt=checkin) | 
                Q(check_in__lt=checkout) & Q(check_out__gte=checkout) | 
                Q(check_in__gt=checkin) & Q(check_out__lt=checkout))
            else:
                reservas = reservas.filter(Q(check_in__lte=checkin) & Q(check_out__gt=checkin))
        else:
            reservas = reservas.filter(Q(check_in__lte=checkin) & Q(check_out__gt=checkin))
    else:
        reservas=reservas.none()

    data = {
        'configuracion': configuracion,
        'filtro': filtro,
        'entity': qs,
        'paginator': paginator,
        'reservas': reservas,
        'checkin':checkin,
    }
    return render(request, 'departamento/inicio.html', data)

# Vista página de nosotros.


def nosotros(request):
    configuracion = Configuration.objects.last()
    data = {
        'configuracion': configuracion,
    }
    return render(request, 'departamento/nosotros.html', data)

def valid_param(param):
    return param != '' and param is not None

class ProfileView(UpdateView):
    model = Huesped
    form_class = profileModifyForm
    template_name = 'departamento/perfil_cliente.html'
    success_url = reverse_lazy('inicio')
    #fields = '__all__'

    def get_object(self):
        huesped, created = Huesped.objects.get_or_create(user=self.request.user)
        return huesped

#Verificación de Información

def verificacionPerfil(request):
    verif = 0
    usuario = get_object_or_404 (Huesped, id = request.user.id)

    if usuario.nombre is None:
        verif = 0
    else:
        verif = 1                   
    
    return verif

#Modificación de perfil para la reserva.

def modify(request):

    usuario = get_object_or_404 (Huesped, id = request.user.id)
    if request.method == 'POST':

        #Llama función para verificar si el perfil está completo.
        verif = verificacionPerfil(request)

        #Creamos instancia del formulario para rescatar los datos.
        form = profileModifyForm(request.POST, instance=usuario)

        #Diccionario de datos para sacar la información, para luego utilizarla en el template.
        context = {
            'form': form,
            'verif': verif
        }
        
        if form.is_valid():

            # Toma cada uno de los datos rescatados desde el formulario creado en la vista.
            formularioModify = form.save(commit=False)
            formularioModify.user = User.objects.get(pk=request.user.id)
            formularioModify.nombre = request.POST.get('nombre')
            formularioModify.apellido = request.POST.get('apellido')
            formularioModify.tipo_documento = request.POST.get('tipo_documento')
            formularioModify.numero_documento = request.POST.get('numero_documento')
            formularioModify.email = request.POST.get('email')
            formularioModify.telefono = request.POST.get('telefono')

            # Guarda los datos en la base de datos.
            formularioModify.save()
            print(context)
            return redirect ('inicio')

    else:

        form = profileModifyForm

    

    return render(request, "departamento/perfil_cliente.html", context)

core/homepage/templates/departamento/inicio.html
{% extends 'base/base.html' %}
{% load static %}

{% block titulo %} - Principal {% endblock %}

{% block contenido %}

<style>
  .link{
    color: darkmagenta;
  }

  #myImg {
    border-radius: 5px;
    cursor: pointer;
    transition: 0.3s;
  }
  
  #myImg:hover {opacity: 0.7;}
  
  /* The Modal (background) */
  .modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
  }
  
  /* Modal Content (image) */
  .modal-content {
    margin: auto;
    display: block;
    width: 80%;
    max-width: 700px;
  }
  
  /* Caption of Modal Image */
  #caption {
    margin: auto;
    display: block;
    width: 80%;
    max-width: 700px;
    text-align: center;
    color: #ccc;
    padding: 10px 0;
    height: 150px;
  }
  
  /* Add Animation */
  .modal-content, #caption {  
    animation-name: zoom;
    animation-duration: 0.6s;
  }
  
  @keyframes zoom {
    from {transform: scale(0.1)} 
    to {transform: scale(1)}
  }
  
  /* The Close Button */
  .close {
    position: absolute;
    top: 15px;
    right: 35px;
    color: #f1f1f1;
    font-size: 40px;
    font-weight: bold;
    transition: 0.3s;
  }
  
  .close:hover,
  .close:focus {
    color: #bbb;
    text-decoration: none;
    cursor: pointer;
  }
  
  /* 100% Image Width on Smaller Screens */
  @media only screen and (max-width: 700px){
    .modal-content {
      width: 100%;
    }
  }
</style>
<!--Barra divisora-->
<div class="b-example-divider"></div>
<br/>
<div class="container-fluid">
  <div class="row">
<div class="col-12 col-md-4 col-lg-3 g-4 mx-2">
  <h5>Filtro de Habitaciones</h5>
  <form method="GET" id="FiltroHabitacion">
    {% csrf_token %}
    <div class="col-12">
    {{filtro.form}}
    <label for="CheckIn">Fecha de Check-In:</label>
    <input type="date" class="form-control" id="CheckIn" name="checkin">
    <label for="CheckIn">Fecha de Check-Out:</label>
    <input type="date" class="form-control" id="CheckOut" name="checkout">
    </div>    
    <button type="submit" class="btn-color pt-2 my-3 text-center"><i class="fas fa-search"> </i> Buscar</button> 
  </form>
  <a href="/"><button class="btn-color pt-2 my-3 text-center"><i class="fas fa-search-minus"> </i> Remover filtro</button></a>
</div>
<br>
<!--style="border-style: solid; border-width: 1px;"-->

<!--Habitaciones-->
<div class="row col-12 col-md-8 g-4 mx-2">
  {% for d in entity %}
    <div id="carta{{forloop.counter}}" class="col-12 col-md-6">
      <div class="card">
        <img class="card-img-top" src="{{ d.tipo_habitacion.imagen.url }}" alt="Sin Imagen" width="200" height="300">
        <div class="card-body">
          <h5 class="card-title">Habitacion N° {{d.numero_habitacion}} - {{d.tipo_habitacion}}</h5>
          <div class="card-text">{{d.desc}}</div>
          <div class="card-text">Tarifa diara: ${{d.tipo_habitacion.tarifa}} + Impuestos</div>
          <div class="card-text">Servicios: {{d.servicio_habitacion}}</div>
          <div class="card-text">Para {{d.capacidad}} personas</div>
          <div class="card-text">Piso: {{d.piso}}</div>
          <div class="row justify-content-center">
            <div class="col-6">
              <button class="btn-color pt-2 my-3 text-center" type="submit">Reservar <i class="fas fa-sign-in-alt"></i></button>
            </div>
          </div>
        </div>
      </div><!-- Fin card -->
    </div>
    <!---->
    {% for f in reservas %}
      {% if d.id == f.habitacion.id%}
      <script>
        $("#carta{{forloop.parentloop.counter}}").remove();
      </script>
      {% endif %}
    {% endfor %}
    
  {% endfor %}
</div>
</div>
<!-- ^ FIn de Container-fluid-->
<!-- Paginación -->
<br/>
<div class="row">
  {% include 'departamento/paginator.html' %}
</div>
</div>


<br>

<!-- Imagen Modal -->
<div id="myModal" class="modal">
  <span class="close">&times;</span>
  <img class="modal-content" id="img01">
  <div id="caption"></div>
</div>
  
<script>
  //Obtener fecha dia de hoy
  var today = new Date();
  var dd = String(today.getDate()).padStart(2, '0');
  var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
  var yyyy = today.getFullYear();
  //Establecer valores minimos para checkin y checkout
  document.getElementById("CheckIn").min = yyyy+"-"+mm+"-"+dd;
  document.getElementById("CheckOut").min = yyyy+"-"+mm+"-"+dd;
  //Dar el valor por el que se buscó al campo de checkin y al de checkout
  document.getElementById("CheckIn").value = '{{request.GET.checkin}}';
  document.getElementById("CheckOut").value = '{{request.GET.checkout}}';
  
  // Script Modal
  var modal = document.getElementById('myModal');
  
  // Get the image and insert it inside the modal - use its "alt" text as a caption
  var img = document.getElementById('myImg')
  var modalImg = document.getElementById("img01");
  var captionText = document.getElementById("caption");
  img.onclick = function(){
    modal.style.display = "block";
    modalImg.src = this.src;
    captionText.innerHTML = this.alt;
  }
  
  // Get the <span> element that closes the modal
  var span = document.getElementsByClassName("close")[0];
  
  // When the user clicks on <span> (x), close the modal
  span.onclick = function() { 
    modal.style.display = "none";
  }
</script>

{% if messages %}
  {% for m in messages %}
    <script>
      Swal.fire({
        icon: 'success',
        title: '!!!Felicidades!!!',
        text: '{{m}}',
      })
    </script>
  {% endfor %}
{% endif %}


<!--   Codigo para cargar multiples imagenes  - Esta aca para pasar a otra plantilla
      {% for ima in imagen %}
        {% if d.tipo_habitacion == ima.tipo_habitacion %}
        <img class="card-img-top" src="{{ ima.imagen.url }}" alt="Sin Imagen" width="200" height="300">
        {% endif %}
      {% endfor%}

        {% if d.imagenes %}
        <h5>Más imagenes:</h5>

        <div class="row justify-content-center">
          <div class="col-lg-12">
            <img id="myImg" src="{{ d.imagenes.first.imagen.url }}" alt='{{d.tipo_hospedaje}}: {{d.nombre}} <br> Dirección: {{d.direccion}}' width="100" height="50"> 
            <img id="myImg" src="{{ d.imagenes.last.imagen.url }}" alt="{{d.nombre}} {{d.direccion}}" width="100" height="50">
          </div>
        </div>

        {% endif %}
      -->
{% endblock %}

core/homepage/templates/departamento/registro.html
{% extends 'departamento/login.html' %}
{% load static %}

{% block titulo %} - Registro {% endblock %}

{% block contenido %}
<!--Formulario de registro de usuarios-->
<div id="fondo">
  <div class="row justify-content-center">
    <div id="registro" class="col-md-6 text-center text-dark mb-2">
      <a href="{% url 'inicio' %}">
      <img src="{% static '/img/llave.png' %}" alt="Logo" width="100">
      </a>
      <h5 class="heading-section">Registrate en Reserva Fácil</h5><br>
      <form action="" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1"><i class="fas fa-at"></i></span>
          <input type="text" name="username" class="form-control" placeholder="Escoge un nombre de usuario" aria-label="Username" aria-describedby="basic-addon1" required>
        </div>
        <!--
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1"><i class="fas fa-user"></i></span>
          <input type="text" name="first_name" class="form-control" placeholder="Escribe tu nombre" aria-label="first_name" aria-describedby="basic-addon1" maxlength="150" id="id_first_name" required>
        </div>
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1"><i class="far fa-user"></i></span>
          <input type="text" name="last_name" class="form-control" placeholder="Escribe tu apellido" aria-label="last_name" aria-describedby="basic-addon1"autofocus="" required="" maxlength="150" id="id_last_name">
        </div>
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1"><i class="far fa-envelope"></i></span>
          <input type="email" name="email" value="ejemplo@gmail.com" class="form-control" placeholder="Escribe tu correo electrónico" aria-label="email" aria-describedby="basic-addon1" required>
        </div>
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1"><i class="fas fa-phone"></i></span>
          <input type="number" name="telefono" required="" id="id_telefono" class="form-control" placeholder="Escribe tu telefono" aria-label="telefono" aria-describedby="basic-addon1" required>
        </div>
        -->
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1"><i class="fas fa-lock"></i></span>
          <input type="password" name="password1" class="form-control input_clave" placeholder="Escribe una contraseña" aria-label="Username" aria-describedby="basic-addon1" autocomplete="new-password" required="" id="id_password1" required>
          <span class="input-group-text" id="basic-addon1"><i class="icono fas fa-eye-slash" onclick="toggle()"></i></span>
        </div>
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1"><i class="fas fa-lock"></i></span>
          <input type="password" name="password2" class="form-control input_clave2" placeholder="Repite la contraseña" aria-label="Username" aria-describedby="basic-addon1" autocomplete="new-password" required="" id="id_password2" required>
          <span class="input-group-text" id="basic-addon1"><i class="icono2 fas fa-eye-slash" onclick="toggle2()"></i></span>
        </div>
        <button class="btn-color pt-2 my-3" type="reset">Limpiar <i class="fas fa-eraser"></i></button>
        <button class="btn-color pt-2 my-3" type="submit">Registrarse <i class="fas fa-sign-in-alt"></i></button>
        <p>¿Ya tienes una cuenta? <a href="{% url 'login' %}">Inicia sesión</a></p>
      </form>
    </div>
  </div>
</div>


<script>
  /* Ocultar/mostrar contraseña password 1*/
  var ojoState = false;
    function toggle() {
      var ojo = document.querySelectorAll('.icono');
      var input = document.querySelectorAll('.input_clave');

      if (ojoState) {
        input.forEach(i => {
          i.setAttribute('type', 'password');
        })
        ojo.forEach(o => {
          o.classList.remove('fa-eye');
          o.classList.add('fa-eye-slash');
        })
        ojoState = false;
      }
      else {
        input.forEach(i => {
          i.setAttribute('type', 'text');
        })
        ojo.forEach(o => {
          o.classList.add('fa-eye');
          o.classList.remove('fa-eye-slash');
        })
        ojoState = true;
      }
    }
  
  /* Ocultar/mostrar contraseña password 2*/
  var ojoState = false;
    function toggle2() {
      var ojo = document.querySelectorAll('.icono2');
      var input = document.querySelectorAll('.input_clave2');

      if (ojoState) {
        input.forEach(i => {
          i.setAttribute('type', 'password');
        })
        ojo.forEach(o => {
          o.classList.remove('fa-eye');
          o.classList.add('fa-eye-slash');
        })
        ojoState = false;
      }
      else {
        input.forEach(i => {
          i.setAttribute('type', 'text');
        })
        ojo.forEach(o => {
          o.classList.add('fa-eye');
          o.classList.remove('fa-eye-slash');
        })
        ojoState = true;
      }
    } 

            {% if form.errors %}
            var errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                errors += '{{ error }}\n';
            {% endfor %}
            Swal.fire({
                title: 'Error!',
                text: errors,
                icon: 'error'
            });
        {% endif %}

</script>

{% endblock %}